Script started on Tue 28 Mar 2017 07:26:32 PM PDT
]0;dc8291@klaatu:~[?1034h[dc8291@klaatu ~]$ whoami
dc8291
]0;dc8291@klaatu:~[dc8291@klaatu ~]$ echo $SHELL
/bin/bash
]0;dc8291@klaatu:~[dc8291@klaatu ~]$ pwd
/homes/dc8291
]0;dc8291@klaatu:~[dc8291@klaatu ~]$ uname -a
Linux klaatu.cs.washington.edu 4.4.52-1.el7.elrepo.x86_64 #1 SMP Sun Feb 26 08:48:14 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
]0;dc8291@klaatu:~[dc8291@klaatu ~]$ gcc --version -std=c11
gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

]0;dc8291@klaatu:~[dc8291@klaatu ~]$ exit
exit

Script done on Tue 28 Mar 2017 07:26:56 PM PDT
